# Numpy 튜토리얼 (1) - 배포용

<span style="color:red">
    본 자료는 교재 "파이썬으로 배우는 머신러닝의 교과서" chapter 2의 내용과 Stanford 강의 "CS231n, Python Numpy Tutorial"의 한글버전(http://aikorea.org/cs231n/python-numpy-tutorial/)을 파이썬 3 버전에 맞게 수정한 것과, TAEWAN.KIM 블로그 자료 "파이썬 데이터 사이언스 Cheat Sheet: NumPy 기초, 기본", http://taewan.kim/post/numpy_cheat_sheet/, 및 그 외에 다른 참고자료들을 일부 추가하여 만들었습니다.
</span>

참고 자료: 
- 이토마코토/박광수, 파이썬으로 배우는 머신러닝의 교과서, chapter 2, 한빛미디어, 2018
- Stanford university, CS231n, Python Numpy Tutorial,의 한글버전 (http://aikorea.org/cs231n/python-numpy-tutorial/)
- TAEWAN.KIM, 파이썬 데이터 사이언스 Cheat Sheet: NumPy 기초, 기본, http://taewan.kim/post/numpy_cheat_sheet/
- Numpy manual https://docs.scipy.org/doc/numpy/contents.html

**리스트로 벡터행렬 연산을 하는 경우의 문제점**:

In [1]:
[1,2] + [3,4] #[4,6]을 원했던 거다.   # 1차원 리스트에서의 +는 벡터 덧셈이 아니라 list concatenation이 됨

[1, 2, 3, 4]

In [27]:
[[1,2], [3,4]] + [[5,6], [7,8]] #[[6,7],[10,11]] 원했다    # 2차원 리스트(리스트의 리스트)에서도 마찬가지로 list concatenation이 일어남.

[[1, 2], [3, 4], [5, 6], [7, 8]]

Numpy는 파이썬이 벡터, 행렬 등으로 계산과학분야에 이용될때 핵심 역할을 하는 라이브러리입니다. Numpy는 고성능의 다차원 배열 객체와 이를 다룰 도구를 제공합니다.

## 배열

In [2]:
#리스트에서 [:]는 복사인데, numpy는 [:]슬라이싱 하면??? 9월 25일 강의 듣기

Numpy 배열은 동일한 자료형을 가지는 값들이 격자판 형태로 있는 것입니다. 각각의 값들은 튜플 형태로 색인 됩니다. rank는 배열이 몇 차원인지를 의미합니다; shape는 는 각 차원의 크기를 알려주는 정수들이 모인 튜플입니다.

파이썬의 리스트를 중첩해 Numpy 배열을 초기화 할 수 있고, 대괄호를 통해 각 요소에 접근할 수 있습니다:

In [2]:
import numpy as np    # 파이썬에서 NumPy를 사용할 때, numpy 모듈을 “np”로 임포트하여 사용합니다.

a = np.array([[1, 2, 3]])    # rank가 1인 배열 생성
print (a)
print (type(a))            # 출력 "<type 'numpy.ndarray'>"
print (a.ndim)             # a의 차원(rank): 출력 1
print (a.shape)            # 출력 "(3,)" = shape의 결과는 항상 tuple 형태.
print (a[0][0], a[0][1], a[0][2])   # 출력 "1 2 3"
a[0] = 5                   # 요소를 변경
print (a)                  # 출력 "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])   # rank가 2인 배열 생성
print (b)
print (b.ndim)             # b의 차원(rank): 출력 2
print (b.shape)            # 출력 "(2, 3)"
w, h = b.shape
print ("w=",w,"h=",h)
print (b[0])               # 출력 "[1 2 3]""
print (b[0][0], b[0][1], b[1][0])   # 출력 "1 2 4"
print (b[0,0], b[0,1], b[1,0])   # 출력 "1 2 4"

[[1 2 3]]
<class 'numpy.ndarray'>
2
(1, 3)
1 2 3
[[5 5 5]]
[[1 2 3]
 [4 5 6]]
2
(2, 3)
w= 2 h= 3
[1 2 3]
1 2 4
1 2 4


**실습문제**: 1부터 9까지의 숫자를 가지는 3x3 행렬을 numpy 객체 A로 생성하여라. 
- A의 모든 원소를 출력하라.
- A의 차원(rank)를 출력하라.
- A의 shape를 출력하라.
- A의 모든 원소에 대해 첫번째 행은 10을 더하고, 두번째 행은 20을 더하고, 세번째 행은 30을 더한 뒤, A의 모든 원소를 출력하라.

In [3]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(A.ndim)
print(A.shape)
A[0,:]+= 10
A[1,:]+= 20
A[2,:]+= 30
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
[[11 12 13]
 [24 25 26]
 [37 38 39]]


**np.arange()에 관하여**

In [22]:
print(np.arange(10))      # 연속된 정수 벡터의 생성, cf) list형의 range(10) 

[0 1 2 3 4 5 6 7 8 9]


In [23]:
print(np.arange(5, 10))

[5 6 7 8 9]


In [5]:
print(np.arange(1, 10, 2))

[1 3 5 7 9]


In [6]:
j = np.array([4, 5, 6])
for i in np.arange(1,5): # arange=1~3
    print(i)
    print(i + j) #1 + [4,5,6] =>[1,1,1]+[4,5,6]=[5,6,7]

1
[5 6 7]
2
[6 7 8]
3
[7 8 9]
4
[ 8  9 10]


리스트의 중첩이 아니더라도 Numpy는 배열을 만들기 위한 다양한 함수를 제공합니다.

In [6]:
import numpy as np

print (np.zeros(10)) # 출력 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

a = np.zeros((2,2))  # 모든 값이 0인 배열 생성, 2차원 배열인 경우 튜플(2,2)로 차원을 나타냄, 따라서 안에 ()가 하나 더 있음
print (a)              # 출력 "[[ 0.  0.] ()갯수 주의하기!
                     #       [ 0.  0.]]"
print (np.ones(10))

b = np.ones((3,3))   # 모든 값이 1인 배열 생성 #2 dimention임
print (b)              # 출력 "[[ 1.  1.]]"
print(b.ndim)    # 2임
c = np.full((2,2), 7) # 모든 값이 특정 상수인 배열 생성
print (c)               # 출력 "[[ 7.  7.]
                      #       [ 7.  7.]]"

d = np.eye(2)        # 2x2 단위행렬 생성
print (d)              # 출력 "[[ 1.  0.]
                     #       [ 0.  1.]]"
d = np.identity(2)   # np.eye(2)와 같은 결과
print (d) 

e = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print (e)                     # 임의의 값 출력 "[[ 0.91940167  0.08143941]
                            #                  [ 0.68744134  0.87236687]]"

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[0.96757695 0.01424095]
 [0.01622539 0.44911506]]


In [21]:
A = np.ones(5)
print(A)
print(A.ndim)
B = np.ones((1,5))
print(B)
print(B.ndim)
print(A.shape)
print(B.shape)
C = np.ones((4,4))
print(C)
print(C.ndim) #행과 열 2차원
print(C.shape)

[1. 1. 1. 1. 1.]
1
[[1. 1. 1. 1. 1.]]
2
(5,)
(1, 5)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2
(4, 4)


**실습문제**: 5x5 행렬을 하나 생성하여 모든 행을 0부터 4까지의 정수로 채우시오.

In [24]:
import numpy as np

a = np.zeros((5,5))
print(a)
for i in range(0,5):
    for j in range(0,5):
        a[i,j] = j
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**실습문제**: 대각요소(diagonal element) 위는 1로 채우고, 아래는 0으로 채운 삼각행렬(triangular matrix)를 만드시오. (슬라이싱 기능을 사용하지 말고 for loop을 이용하시오.)

In [25]:
A=np.ones((10,10))
print(A.shape[0])
for i in range(1,A.shape[0]):
    for j in range(i):
        A[i,j] = 0
A
#j => 0
#j => 0 1
#j => 0 1 2
#슬라이싱은 영상에 있음

10


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**실습문제**: 1부터 n^2까지의 숫자를 가지는 nxn 행렬을 numpy 객체 A로 생성하여라. 
- A의 모든 원소에 대해 첫번째 행은 10을 더하고, 두번째 행은 20을 더하고, 세번째 행은 30을 더하고, ..., 그런 후 A의 모든 원소를 출력하라.

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A[0,:]+= 10
A[1,:]+= 20
A[2,:]+= 30
print(A)
for i in np.arange(0,3):
    for j in np.arange(0,3):
        print(A[i,j])

[[11 12 13]
 [24 25 26]
 [37 38 39]]
11
12
13
24
25
26
37
38
39


### 요소가 랜덤인 배열의 생성

In [26]:
np.random.rand(2, 3)      # (2,3) 행렬의 요소를 0과 1사이의 균등분포로 랜덤하게 생성

array([[0.07076156, 0.37039446, 0.99996179],
       [0.85442973, 0.9357876 , 0.80684542]])

In [27]:
np.random.randn(2, 3)      # (2,3) 행렬의 요소를 평균 0, 분산 1의 가우스분포로 랜덤하게 생성

array([[ 0.79350852, -0.33737359, -0.94493575],
       [-0.25694537, -0.03574423, -0.65963874]])

In [28]:
np.random.randint(10, 100, 5)      # 10부터 100까지 정수 5개를 랜덤하게 생성

array([74, 27, 84, 36, 29])

In [29]:
np.random.randint(10, 100, (2,5))      # 10부터 100까지 정수를 (2,5) 행렬로 랜덤하게 생성

array([[18, 83, 45, 92, 22],
       [67, 11, 75, 98, 95]])

**실습문제**: 원소들의 값이 랜덤인 10x10 행렬을 생성하고, 최대값과 최소값을 찾으시오. (np.max()와 np.min() 함수를 사용하지 말고 for loop을 이용하시오.)

In [30]:
A = np.random.rand(10,10)
print(A)
a = 0
for i in np.arange(0,10):
    for j in np.arange(0,10):
        if A[i,j] >= a:
            a = A[i,j]
print(a)
b = A[i,j]
for i in np.arange(0,10):
    for j in np.arange(0,10):
        if A[i,j] <= b:
            b = A[i,j]
print(b)

[[3.75612066e-01 1.19968696e-01 6.54219056e-01 7.52651793e-01
  6.83591643e-02 3.28640212e-01 9.45748991e-01 9.39256789e-01
  7.38354914e-01 6.73062850e-01]
 [7.68669524e-01 1.96986518e-01 5.53971129e-01 1.32886658e-01
  6.00249466e-01 6.67350631e-01 1.94106031e-02 2.27165562e-01
  9.99304276e-01 6.13225787e-01]
 [4.32244841e-01 9.61585124e-03 3.50444069e-01 2.26292794e-02
  2.97194859e-01 7.19536768e-01 2.60293278e-01 2.59946590e-01
  1.93342795e-01 6.14259468e-01]
 [2.15718722e-01 8.95042894e-01 5.50481084e-01 5.41296560e-01
  9.03216940e-01 9.03882885e-01 4.53099297e-01 9.20110993e-01
  3.98007794e-01 3.66637468e-01]
 [6.59676775e-01 4.91804277e-01 5.94696289e-01 3.03701939e-01
  3.82894924e-02 4.28320528e-02 9.68872399e-04 3.11134770e-01
  8.61746317e-01 7.14492321e-01]
 [2.14264680e-01 3.73290209e-01 4.87816951e-01 2.95287787e-02
  6.70464714e-01 2.29811273e-01 9.97243030e-01 8.89725054e-01
  7.64693820e-01 2.49056116e-01]
 [4.69965232e-01 9.40138542e-01 6.06674749e-01 4.81007214e

**random number 생성 시 seed 값 주기**: 

    np.random.seed(seed_value)

In [31]:
A = np.ones((10,10))
A.shape[0]

10

In [32]:
# seed 값을 설정하여 아래에서 난수가 재연 가능하도록 함
np.random.seed(100) # 3 5 7 1 3     #4 5 2 5 3  #이해 못함 영상 한번 보기

In [33]:
np.random.randn(2, 3)

array([[-1.74976547,  0.3426804 ,  1.1530358 ],
       [-0.25243604,  0.98132079,  0.51421884]])

In [34]:
np.random.randint(10, 100, 5)

array([34, 25, 70, 68, 26])

## 자료형

NumPy는 다음과 같은 데이터 타입을 지원합니다. 배열을 생성할 때 dtype속성으로 다음과 같은 데이터 타입을 지정할 수 있습니다:
- np.int32 : 32 비트 정수 타입
- np.float64 : 64 비트 부동 소수 타입
- np.complex : 복소수 (128 float)
- np.bool : 불린 타입 (True, False)
- np.object : 파이썬 객체 타입
- np.string_ : 고정자리 스트링 타입
- np.unicode_ : 고정자리 유니코드 타입


Numpy는 배열이 생성될 때 자료형을 스스로 추측합니다, 그러나 배열을 생성할 때 명시적으로 특정 자료형을 지정할 수도 있습니다. 

In [2]:
import numpy as np

x = np.array([1, 2])  # Numpy가 자료형을 추측해서 선택
print (x.dtype)         # 출력 "int32"

x = np.array([1.0, 2.0])  # Numpy가 자료형을 추측해서 선택
print (x.dtype)             # 출력 "float64"

x = np.array([1, 2], dtype=np.int64)  # 특정 자료형을 명시적으로 지정 #longint
print (x.dtype)                         # 출력 "int64"

int32
float64
int64


## 배열의 속성 확인

![대체 텍스트](attribute.JPG)

In [39]:
#데모 배열 객체 생성
arr = np.random.random((5,2,3))
arr

array([[[0.97772095, 0.47738415, 0.23895263],
        [0.93235066, 0.13671513, 0.17192781]],

       [[0.50305449, 0.05585289, 0.29766707],
        [0.92771357, 0.38659638, 0.46212547]],

       [[0.57862899, 0.1139206 , 0.36841365],
        [0.36074842, 0.88001849, 0.27454204]],

       [[0.22458118, 0.81397318, 0.05820075],
        [0.73015342, 0.03267909, 0.59998723]],

       [[0.03054111, 0.85960489, 0.43977952],
        [0.56044466, 0.81740526, 0.0890063 ]]])

In [46]:
#배열 타입 조회
type(arr)

numpy.ndarray

In [47]:
# 배열의 차원 수 
arr.ndim

3

In [48]:
# 배열의 shape 확인
arr.shape

(5, 2, 3)

In [7]:
# 배열의 길이: shape(k, m, n) ==> k
len(arr)

5

In [8]:
# 배열의 요소 수: shape(k, m, n) ==> k*m*n
arr.size

30

In [9]:
# 배열 타입 확인
arr.dtype

dtype('float64')

In [37]:
# 배열 요소를 int로 변환
# 요소의 실제 값이 변환되는 것이 아님
# View의 출력 타입과 연산을 변환하는 것
arr.astype(np.int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [11]:
np.int32(arr)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [12]:
# np.float으로 타입을 다시 변환하면 np.int 변환 이전 값으로 모든 원소 값이 복원됨
arr.astype(np.float)

array([[[0.58403552, 0.48669189, 0.23910756],
        [0.84334134, 0.72136029, 0.36715268]],

       [[0.73029773, 0.62699657, 0.21056904],
        [0.71537227, 0.60831941, 0.953575  ]],

       [[0.66339792, 0.68405949, 0.45335461],
        [0.40957499, 0.06457012, 0.63736258]],

       [[0.32560103, 0.88429382, 0.34990223],
        [0.52589402, 0.85216698, 0.03109399]],

       [[0.41037066, 0.78179478, 0.6269085 ],
        [0.07705805, 0.8422231 , 0.3462618 ]]])

In [13]:
np.float64(arr)

array([[[0.58403552, 0.48669189, 0.23910756],
        [0.84334134, 0.72136029, 0.36715268]],

       [[0.73029773, 0.62699657, 0.21056904],
        [0.71537227, 0.60831941, 0.953575  ]],

       [[0.66339792, 0.68405949, 0.45335461],
        [0.40957499, 0.06457012, 0.63736258]],

       [[0.32560103, 0.88429382, 0.34990223],
        [0.52589402, 0.85216698, 0.03109399]],

       [[0.41037066, 0.78179478, 0.6269085 ],
        [0.07705805, 0.8422231 , 0.3462618 ]]])

## 배열 인덱싱

Numpy는 배열을 인덱싱하는 몇 가지 방법을 제공합니다.

**슬라이싱:** 파이썬 리스트와 유사하게, Numpy 배열도 슬라이싱이 가능합니다. Numpy 배열은 다차원인 경우가 많기에, 각 차원별로 어떻게 슬라이스할건지 명확히 해야 합니다:

In [41]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# 슬라이싱을 이용하여 첫 두 행과 1열, 2열로 이루어진 부분배열을 만들어 봅시다;
# b는 shape가 (2,2)인 배열이 됩니다:
# [[2 3]
#  [6 7]]
b = a[0:2, 1:3] # 0,1행
print (b)

# 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조합니다, 즉 슬라이싱된 배열을 수정하면
# 원본 배열 역시 수정됩니다.
print (a[0, 1])   # 출력 "2"
b[0, 0] = 77    # b[0, 0]은 a[0, 1]과 같은 데이터입니다
print (a[0, 1])   # 출력 "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


정수를 이용한 인덱싱과 슬라이싱을 혼합하여 사용할 수 있습니다. 하지만 이렇게 할 경우, 기존의 배열보다 낮은 rank의 배열이 얻어집니다.

In [42]:
import numpy as np

# 아래와 같은 요소를 가지는 rank가 2이고 shape가 (3, 4)인 배열 생성
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
# 배열의 중간 행에 접근하는 두 가지 방법이 있습니다.
# 정수 인덱싱과 슬라이싱을 혼합해서 사용하면 낮은 rank의 배열이 생성되지만,
# 슬라이싱만 사용하면 원본 배열과 동일한 rank의 배열이 생성됩니다.
row_r1 = a[1, :]    # 배열a의 두 번째 행을 rank가 1인 배열로
row_r2 = a[1:2, :]  # 배열a의 두 번째 행을 rank가 2인 배열로
print (row_r1, row_r1.shape)  # 출력 "[5 6 7 8] (4,)"
print (row_r2, row_r2.shape)  # 출력 "[[5 6 7 8]] (1, 4)"

# 행이 아닌 열의 경우에도 마찬가지입니다:
col_r1 = (a[:, 1])
col_r2 = (a[:, 1:2])
print (col_r1, col_r1.shape)  # 출력 "[ 2  6 10] (3,)"
print (col_r2, col_r2.shape)  # 출력 "[[ 2]
                            #       [ 6]
                            #       [10]] (3, 1)"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**실습문제**: 경계선(border)의 원소는 모두 1이고, 내부 원소는 모두 0인 (10,10) 행렬을 생성하시오.

In [46]:
import numpy as np
A = np.zeros((10,10))
A[0,:]=1
A[9,:]=1
A[:,0]=1
A[:,9]=1
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**실습문제**: 대각요소(diagonal element) 위는 1로 채우고, 아래는 0으로 채운 삼각행렬(triangular matrix)를 만드시오. (슬라이싱 기능을 사용하시오.)

In [43]:
import numpy as np

A = np.ones((10,10))
for i in np.arange(1,10):
    A[i,:i]=0
A   

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**실습문제**: 8x8 행렬을 생성해서 체커보드(checkerboard) 패턴으로 0과 1로 초기화 하시오. (예를들어 아래는 4x4 행렬의 체커보드 패턴이다.)

    1 0 1 0
    0 1 0 1
    1 0 1 0
    0 1 0 1

In [49]:
A = np.zeros((8,8))
A[0::2,0::2]=1
A[1::2,1::2]=1
A

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**불리언 배열 인덱싱:** 불리언 배열 인덱싱을 통해 배열 속 요소를 취사선택할 수 있습니다. 불리언 배열 인덱싱은 특정 조건을 만족하게 하는 요소만 선택하고자 할 때 자주 사용됩니다.

In [58]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
bool_idx = (a > 2)  # 2보다 큰 a의 요소를 찾습니다;
                    # 이 코드는 a와 shape가 같고 불리언 자료형을 요소로 하는 numpy 배열을 반환합니다,
                    # bool_idx의 각 요소는 동일한 위치에 있는 a의
                    # 요소가 2보다 큰지를 말해줍니다.

print (bool_idx)      # 출력 "[[False False]
                    #       [ True  True]
                    #       [ True  True]]"

# 불리언 배열 인덱싱을 통해 bool_idx에서
# 참 값을 가지는 요소로 구성되는
# rank 1인 배열을 구성할 수 있습니다.
print(a[bool_idx])  # 출력 "[3 4 5 6]"

# 위에서 한 모든것을 한 문장으로 할 수 있습니다:
print(a[a > 2])     # 출력 "[3 4 5 6]"

# 불리언 배열 인덱싱을 통해 요소를 수정하는 것도 가능합니다
a[a > 2] = 99
print (a)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[[ 1  2]
 [99 99]
 [99 99]]


**실습문제**: 1부터 10까지의 정수로 구성된 1차원 배열을 생성한 뒤 2과 3의 배수를 음수로 만드시오.

In [50]:
#꼭해보기 중간 공부! 중간 문제
A = np.arange(1,11)
print((A%2==0)|(A%3==0))
print(A[(A%2==0)|(A%3==0)])
A[(A%2==0)|(A%3==0)]*=-1
print(A)

[False  True  True  True False  True False  True  True  True]
[ 2  3  4  6  8  9 10]
[  1  -2  -3  -4   5  -6   7  -8  -9 -10]


## 배열의 형태 변경

In [59]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


위의 배열을 2*5의 행렬로 변경하려면 np.reshape() 함수를 사용하여 다음과 같이 입력합니다.

In [60]:
a.reshape(2, 5)      # 2*5의 행렬로 변환

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a.reshape(2, -1)      # 행렬의 마지막 차수를 -1로 하면 시스템에서 알아서 5로 계산함

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

np.reshape() 함수를 사용하여 행렬을 벡터로도 변환할 수 있다. 

In [16]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)    # 행렬을 벡터로 변환도 가능

array([1, 2, 3, 4, 5, 6])

In [19]:
np.reshape(a, -1)   # 벡터의 원소의 개수를 -1로 하면 시스템에서 알아서 6으로 계산함

array([1, 2, 3, 4, 5, 6])