# PyTorch Tensor Basic Usage

- Create Tensor
- Indexing,Joining,Slicing
- Initialization
- Math Operations

## 0. What is tensor?

<img src="tensor.jpg" width="600">

- 파이토치는 텐서를 기본 연산의 단위로 사용함

## 1. Create Tensor
### 1) random numbers

In [1]:
import torch

# torch.rand(sizes) -> U[0,1)
x = torch.rand(2,3)
x

tensor([[0.4376, 0.8867, 0.7016],
        [0.8225, 0.8069, 0.1282]])

In [2]:
# torch.randn(sizes) -> N(0,1)
x = torch.randn(2,3)
x

tensor([[-0.3377,  1.5977,  0.1475],
        [-1.6460,  0.5277,  0.5354]])

In [3]:
# torch.randperm(n) -> permutation of 0~n
x = torch.randperm(5)
x

tensor([1, 2, 3, 4, 0])

### 2) zeros, ones, arange

In [4]:
# torch.zeros(2,3) -> [[0,0,0],[0,0,0]]
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# torch.ones(2,3) -> [[0,0,0],[0,0,0]]
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# torch.arange(start,end,step=1) -> [start,end) with step
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

### 3) Tensor Data Type

<img src="tensor-type.jpg" width="700">

In [7]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor([2,3])
x

tensor([2., 3.])

In [9]:
# tensor.type_as(tensor_type)
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

### 4) Numpy to Tensor, Tensor to Numpy

In [10]:
import numpy as np

# torch.from_numpy(ndarray) -> tensor

x1 = np.ndarray(shape=(2,3), dtype=int,buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)

x2

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [11]:
# tensor.numpy() -> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

### 5) Tensor on CPU & GPU

In [12]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
x_gpu = x.cuda()
x_gpu

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [14]:
x_cpu = x_gpu.cpu()
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 6) Tensor Size

In [15]:
# tensor.size() -> indexing also possible

x = torch.FloatTensor(10,12,3,3)

x.size()    # x.size()[:]

torch.Size([10, 12, 3, 3])

## 2. Indexing, Slicing, Joining
### 1) Indexing

In [16]:
# torch.index_select(input, dim, index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))

In [17]:
x

tensor([[0.7062, 0.6996, 0.3207],
        [0.2384, 0.6421, 0.2921],
        [0.6378, 0.7241, 0.1604],
        [0.7675, 0.3117, 0.6269]])

In [18]:
out

tensor([[0.7062, 0.6996, 0.3207],
        [0.7675, 0.3117, 0.6269]])

In [19]:
# pythonic indexing also works

x[:,0],x[0,:],x[0:2,0:2]

(tensor([0.7062, 0.2384, 0.6378, 0.7675]),
 tensor([0.7062, 0.6996, 0.3207]),
 tensor([[0.7062, 0.6996],
         [0.2384, 0.6421]]))

In [20]:
# torch.masked_select(input, mask)

x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]]) 
out = torch.masked_select(x,mask)

..\aten\src\ATen\native\LegacyDefinitions.cpp:67: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.


In [21]:
x

tensor([[-0.7534,  0.7674, -1.5316],
        [-1.6657,  2.3934,  0.8217]])

In [22]:
mask

tensor([[0, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)

In [23]:
out

tensor([-1.5316,  2.3934])

### 2) Joining

In [24]:
# torch.cat(seq, dim=0) -> concatenate tensor along dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

In [25]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
y

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

In [27]:
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

In [28]:
z2

tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])

In [32]:
# torch.stack(sequence,dim=0) -> stack along new dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack = torch.stack([x,x,x,x],dim=0)

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

### 3) Slicing

In [33]:
# torch.chunk(tensor, chunks, dim=0) -> tensor into num chunks

x_1, x_2 = torch.chunk(z1,2,dim=0)

In [34]:
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

In [35]:
x_1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [36]:
x_2

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

In [37]:
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

In [38]:
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

In [39]:
y_1

tensor([[ 1.],
        [ 4.],
        [-1.],
        [-4.]])

In [40]:
y_2

tensor([[ 2.],
        [ 5.],
        [-2.],
        [-5.]])

In [41]:
y_3

tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])

In [42]:
# torch.split(tensor,split_size,dim=0) -> split into specific size

x1,x2 = torch.split(z1,2,dim=0)

In [43]:
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

In [44]:
x1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [45]:
x2

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

In [46]:
y1,y2 = torch.split(z1,2,dim=1) 

In [47]:
y1

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [-1., -2.],
        [-4., -5.]])

In [48]:
y2

tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])

### 4) squeezing

In [49]:
# torch.squeeze(input,dim=None) -> reduce dim by 1

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(),x2.size()`

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [50]:
# torch.unsqueeze(input,dim=None) -> add dim by 1

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x1.size(),x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

## 3. Initialization

In [51]:
import torch.nn.init as init

x1 = init.uniform(torch.FloatTensor(3,4),a=0,b=9) 
x2 = init.normal(torch.FloatTensor(3,4),std=0.2)
x3 = init.constant(torch.FloatTensor(3,4),3.1415)

x1,x2,x3

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  """


(tensor([[5.0168, 6.0262, 2.0636, 5.3078],
         [3.4351, 7.4271, 0.4748, 0.4319],
         [5.9133, 2.0720, 7.5871, 0.9123]]),
 tensor([[-0.2018,  0.0310, -0.0774,  0.0970],
         [ 0.1486, -0.0635,  0.4851,  0.0365],
         [ 0.2894, -0.1758,  0.0844, -0.3043]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))

## 4. Math Operations
### 1) Arithmetic operations

In [52]:
# torch.add()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

In [53]:
x1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [54]:
add

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [55]:
x1+x2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [56]:
x1-x2

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [57]:
# torch.add() broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10)

In [58]:
x1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [59]:
x2

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [60]:
x1+10

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [61]:
x2-10

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [62]:
# torch.mul() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

x3

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [63]:
x1*x2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [64]:
# torch.mul() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [65]:
# torch.div() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [66]:
x1/x2

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [67]:
# torch.div() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

### 2) Other Math Operations

In [68]:
# torch.pow(input,exponent)

x1 = torch.FloatTensor(torch.ones(3,4))/2
torch.pow(x1,2)

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])

In [69]:
x1**2

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])

In [73]:
# torch.exp(tensor,out=None) 

x1 = torch.FloatTensor(3,4)
torch.exp(x1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
# torch.log(input, out=None) -> natural logarithm

x1 = torch.FloatTensor(3,4)
torch.log(x1)

tensor([[-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf]])

### 3) Matrix operations

In [75]:
# torch.mm(mat1, mat2) -> matrix multiplication

x1 = torch.FloatTensor(torch.ones(3,4))
x2 = torch.FloatTensor(torch.ones(4,5))

torch.mm(x1,x2)

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

In [76]:
# torch.bmm(batch1, batch2) -> batch matrix multiplication

x1 = torch.FloatTensor(torch.ones(10,3,4))
x2 = torch.FloatTensor(torch.ones(10,4,5))

torch.bmm(x1,x2)

tensor([[[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]]])

In [77]:
torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

In [78]:
# torch.dot(tensor1,tensor2) -> dot product of two tensor

x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(3,4)

torch.dot(x1,x2)

RuntimeError: 1D tensors expected, got 2D, 2D tensors at C:\w\1\s\tmp_conda_3.7_112106\conda\conda-bld\pytorch_1572952932150\work\aten\src\TH/generic/THTensorEvenMoreMath.cpp:774

In [80]:
# torch.t(matrix) -> transposed matrix

x1 = torch.FloatTensor(3,4)
x1.t()

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [81]:
# torch.transpose(input,dim0,dim1) -> transposed matrix

x1 = torch.FloatTensor(10,3,4)

x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [82]:
# torch.eig(a,eigenvectors=False) -> eigen_value, eigen_vector

x1 = torch.FloatTensor(4,4)
x1

tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39, 9.7346e-39],
        [1.0745e-38, 1.0102e-38, 9.9184e-39, 1.0102e-38]])

In [83]:
torch.eig(x1,True)

torch.return_types.eig(
eigenvalues=tensor([[ 3.7716e-38,  0.0000e+00],
        [ 2.0820e-39,  0.0000e+00],
        [-6.2230e-40,  0.0000e+00],
        [ 1.3077e-40,  0.0000e+00]]),
eigenvectors=tensor([[-0.4834,  0.3225, -0.8295, -0.6809],
        [-0.4562, -0.8542,  0.1804,  0.6984],
        [-0.5160,  0.2844,  0.4833, -0.1426],
        [-0.5403,  0.2922,  0.2142,  0.1680]]))