# numpy

In [7]:
import numpy as np
from datetime import datetime
start = datetime.now()

np.random.seed(0)
N,D = 3,4
x = np.random.randn(N,D)
y = np.random.randn(N,D)
z = np.random.randn(N,D)

a = x*y
b = a+z
c = np.sum(b)

print("a= ",a)
print("b= ",b)
print("c= ",c)

grad_c = 1.0
grad_b = grad_c * np.ones((N,D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_x = grad_a * y
grad_y = grad_a * x

print("grad_x =", grad_x)
print("grad_y =", grad_y)
print("grad_z =", grad_z)
print(datetime.now()-start)


a=  [[ 1.34251038  0.04868913  0.43442581  0.74772853]
 [ 2.79027931  0.20049663  0.297442    0.12927355]
 [ 0.26351668  0.26837482  0.12451648 -1.07931093]]
b=  [[ 3.61226501 -1.40567654  0.48018432  0.56054468]
 [ 4.32305853  1.6698554   0.45238942  0.50743607]
 [-0.62426907 -1.71242165 -0.22339567 -0.92296196]]
c=  6.717008537800067
grad_x = [[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]
grad_y = [[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]
grad_z = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0:00:00.012964


# pytorch

In [8]:
import torch
from torch.autograd import Variable
from datetime import datetime
start = datetime.now()

N,D = 3,4
x = Variable(torch.randn(N,D), requires_grad=True)
y = Variable(torch.randn(N,D), requires_grad=True)
z = Variable(torch.randn(N,D), requires_grad=True)

a = x*y
b = a+z
c = torch.sum(b)

print("a= ",a)
print("b= ",b)
print("c= ",c)

c.backward()

print("grad_x =", x.grad)
print("grad_y =", y.grad)
print("grad_z =", z.grad)
print(datetime.now()-start)

a=  tensor([[ 0.0919, -0.4797, -1.2224, -0.3133],
        [-0.4089, -0.0390,  1.6052,  1.2316],
        [ 0.4981, -0.7964,  0.0960,  1.5216]], grad_fn=<MulBackward0>)
b=  tensor([[-0.4097, -0.1490, -1.7462,  0.5244],
        [-0.0930,  0.4548,  2.0031,  0.8779],
        [-0.5724,  0.0925, -0.7900,  2.8938]], grad_fn=<AddBackward0>)
c=  tensor(3.0864, grad_fn=<SumBackward0>)
grad_x = tensor([[-0.5385,  0.7878,  0.7865,  1.6109],
        [ 1.0173, -0.0499,  0.8144, -1.0111],
        [ 0.6024,  1.0100,  1.4420, -0.7158]])
grad_y = tensor([[-0.1707, -0.6089, -1.5542, -0.1945],
        [-0.4019,  0.7814,  1.9709, -1.2181],
        [ 0.8269, -0.7885,  0.0666, -2.1257]])
grad_z = tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
0:00:00.022939
