# Pytorch Tensor and Gradient 

## 1. Tensor

In [19]:
import torch
X = torch.Tensor(2,3)
X

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
X.data, X.grad, X.grad_fn

(tensor([[0., 0., 0.],
         [0., 0., 0.]]), None, None)

In [21]:
X = torch.tensor([[1,2,3],[4,5,6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
X.data, X.grad, X.grad_fn

(tensor([[1, 2, 3],
         [4, 5, 6]]), None, None)

In [23]:
x_tensor = torch.tensor(data=[2.0, 3.0], requires_grad=True)
x_tensor

tensor([2., 3.], requires_grad=True)

In [24]:
x_tensor.data, x_tensor.grad, x_tensor.grad_fn

(tensor([2., 3.]), None, None)

## 2. Gradient

In [2]:
import torch

In [3]:
x = torch.tensor(data=[2.0, 3.0], requires_grad=True)
y = x**2
z = 2*y+3

In [4]:
target = torch.tensor([3.0, 4.0])
loss = torch.sum(torch.abs(z-target))
loss.backward()

In [5]:
print(x.grad, y.grad, z.grad)    # 계산 그래프의 리프 노드에만 grad 값이 출력됨, 중간 노드는 출력 안 됨

tensor([ 8., 12.]) None None
