# Numpy Vs Pytorch

출처: https://www.arunprakash.org/2017/11/numpy-vs-pytorch.html

In [1]:
import numpy as np
import torch

## 1. Creating a matrix with numpy vs pytorch

In [2]:
arr = [[1,2], [2,3]]

In [3]:
np.array(arr)

array([[1, 2],
       [2, 3]])

In [4]:
torch.Tensor(arr)

tensor([[1., 2.],
        [2., 3.]])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## 2. Random numbers

In [9]:
np.random.rand(2,3)

array([[0.6653657 , 0.30187461, 0.17285606],
       [0.16220414, 0.86191331, 0.55575746]])

In [10]:
torch.rand(2,3)

tensor([[0.1241, 0.3320, 0.2432],
        [0.4280, 0.9623, 0.6103]])

## 3. Seed for reproducibility

***Numpy***

In [11]:
np.random.seed(8)
np.random.randn(2,2)

array([[ 0.09120472,  1.09128273],
       [-1.94697031, -1.38634953]])

In [12]:
np.random.seed(8)
np.random.randn(2,2)

array([[ 0.09120472,  1.09128273],
       [-1.94697031, -1.38634953]])

In [13]:
np.random.randn(2,2)

array([[-2.29649157,  2.4098343 ],
       [ 1.72783617,  2.20455628]])

***PyTorch***

In [14]:
torch.manual_seed(8)
torch.randn(2,2)

tensor([[ 0.2713, -1.2729],
        [ 0.5027,  0.4181]])

In [15]:
torch.manual_seed(8)
torch.randn(2,2)

tensor([[ 0.2713, -1.2729],
        [ 0.5027,  0.4181]])

In [16]:
torch.randn(2,2)

tensor([[-0.6394, -0.6608],
        [-0.1433, -0.1043]])

## 4. from_numpy()

In [17]:
numpy_arr = np.array(np.random.rand(2,2))
numpy_arr

array([[0.76089558, 0.71237457],
       [0.6196821 , 0.42609177]])

In [18]:
type(numpy_arr)

numpy.ndarray

In [19]:
pytorch_arr = torch.from_numpy(numpy_arr)
pytorch_arr

tensor([[0.7609, 0.7124],
        [0.6197, 0.4261]], dtype=torch.float64)

In [20]:
type(pytorch_arr)

torch.Tensor

### How to change the datatype to IntTensor?

In [21]:
numpy_arr = np.array(np.random.rand(2,2), dtype=np.int32)
numpy_arr

array([[0, 0],
       [0, 0]])

In [22]:
type(numpy_arr)

numpy.ndarray

In [23]:
pytorch_arr = torch.from_numpy(numpy_arr)
pytorch_arr

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

In [24]:
type(pytorch_arr)

torch.Tensor

### How to convert torch tensors to numpy array?

In [25]:
torch_tensors = torch.randn(2,2)
torch_tensors

tensor([[-1.5313,  0.6318],
        [-1.3448,  1.4309]])

In [26]:
numpy_arr = torch_tensors.numpy()
numpy_arr

array([[-1.5312546,  0.6318015],
       [-1.3447676,  1.4309413]], dtype=float32)

## 5. Tensor Operations

### How to resize torch tensors?

***Numpy***

In [ ]:
numpy_arr = np.zeros((2,2))
numpy_arr

In [31]:
numpy_arr.reshape(1,4)

array([[0., 0., 0., 0.]])

In [32]:
numpy_arr.shape

(2, 2)

***PyTorch***

In [29]:
torch_ten = torch.zeros((2,2))
torch_ten

tensor([[0., 0.],
        [0., 0.]])

In [30]:
torch_ten.view(1,4)

tensor([[0., 0., 0., 0.]])

In [33]:
torch_ten.size()

torch.Size([2, 2])

### How to do element-wise addition?

***Numpy***

In [34]:
a = np.array([[1,2], [2,3]])
a

array([[1, 2],
       [2, 3]])

In [35]:
b = np.array([[1,2], [2,3]])
b

array([[1, 2],
       [2, 3]])

In [36]:
a+b

array([[2, 4],
       [4, 6]])

In [37]:
np.add(a,b)

array([[2, 4],
       [4, 6]])

***PyTorch***

In [38]:
a = torch.Tensor([[1,2], [2,3]])
a

tensor([[1., 2.],
        [2., 3.]])

In [39]:
b = torch.Tensor([[1,2], [2,3]])
b

tensor([[1., 2.],
        [2., 3.]])

In [40]:
a+b

tensor([[2., 4.],
        [4., 6.]])

In [41]:
torch.add(a,b)

tensor([[2., 4.],
        [4., 6.]])

### How to perform mean operation?

***Numpy***

In [42]:
numpy_arr = np.array([[1,2,3,4,5], [1,2,3,4,9]])
numpy_arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 9]])

In [43]:
numpy_arr.mean()

3.4

In [44]:
numpy_arr.mean(axis=1)

array([3. , 3.8])

In [45]:
numpy_arr.shape

(2, 5)

In [46]:
numpy_arr.mean(axis=1).shape

(2,)

***PyTorch***

In [47]:
torch_ten = torch.Tensor([[1,2,3,4,5],[1,2,3,4,9]])
torch_ten

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 9.]])

In [48]:
torch_ten.mean()

tensor(3.4000)

In [49]:
torch_ten.mean(dim=1)

tensor([3.0000, 3.8000])

In [50]:
torch_ten.size()

torch.Size([2, 5])

In [51]:
torch_ten.mean(dim=1).size()

torch.Size([2])